packages:
  all:
    compiler: [gcc@12.3.0, gcc@13.2.0, nvhpc@23.9]
    providers:
      blas: [cray-libsci, blis]
      lapack: [cray-libsci, openblas]
      mpi: [cray-mpich, openmpi, mpich]
    variants: +cuda cuda_arch=90
    permissions:
      write: group
  numactl:
    require:
    - '%gcc'
  xz:
    require:
    - '%gcc'
  openmpi:
    variants: +cuda fabrics=ofi cuda_arch=90
  mpich:
    variants: +cuda+fortran pmi=cray device=ch4 netmod=ofi cuda_arch=90
  cray-mpich:
    buildable: false
    version: [8.1.30]
    externals:
    - spec: cray-mpich@8.1.30 %gcc@12.3
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
    - spec: cray-mpich@8.1.30 %gcc@13.2
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/gnu/12.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
    - spec: cray-mpich@8.1.30 %cce@18.0.0
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/cray/17.0
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
    - spec: cray-mpich@8.1.30 %nvhpc@23.9
      prefix: /opt/cray/pe/mpich/8.1.30/ofi/nvidia/23.3
      extra_attributes:
        environment:
          prepend_path:
            LD_LIBRARY_PATH: /opt/cray/libfabric/1.15.2.0/lib64/
  libfabric:
    buildable: false
    version: [1.15.2.0]
    externals:
    - spec: libfabric@1.15.2.0
      prefix: /opt/cray/libfabric/1.15.2.0
      modules: [libfabric/1.15.2.0]
  cray-pmi:
    buildable: false
    version: [6.1.15]
    externals:
    - spec: cray-pmi@6.1.15
      prefix: /opt/cray/pe/pmi/6.1.15
      modules: [cray-pmi/6.1.15]
  git:
    externals:
    - spec: git@2.35.3~tcltk
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.4
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  curl:
    externals:
    - spec: curl@8.0.1+gssapi+ldap+nghttp2
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.34
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  binutils:
    externals:
    - spec: binutils@2.41.0~gold~headers
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
  coreutils:
    externals:
    - spec: coreutils@8.32
      prefix: /usr
  zlib:
    externals:
    - spec: zlib@1.2.13
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1l-fips
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.20.4
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.8.0
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.4p1
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.20.2
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+opcode+open+shared+threads
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  slurm:
    buildable: false
    externals:
    - spec: slurm@23.02.6
      prefix: /usr
